import Head from 'next/head'
import { useState } from 'react'
import { Count } from '../components/Count'

export default function Home() {
  const [count, setCount] = useState(0)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex'>
        <Count count={count} />
      </div>
      <button
        id='increment'
        onClick={() => {
          setCount(count + 1)
        }}
        className='p-2'
      >
        +
      </button>
      <button
        id='decrement'
        onClick={() => {
          setCount(count - 1)
        }}
        className='p-2'
      >
        -
      </button>
    </div>
  )
}
